# KUIS 2 Pembelajaran Mesin

## Tentang dataset

Pada sebuah lembaga kemanusiaan berbasis teknologi informasi, dibentuk beberapa tim kemanusiaan yang bertugas untuk terjun ke masyarakat memberikan bantuan dalam bentuk aplikasi komputer atau layanan pelatihan IT.  Kegiatn tersebut dilaksanakan setiap tahun dengan ketentuan anggota organisasi tersebut dapat bergabung ke beberapa tim sebagai ketua atau anggota. Terdapat pula anggota yang sudah tidak aktif di organisasi tersebut (terhapus di database mereka â€”> label N/A).  Organisasi tersebut juga melakukan rekrutmen volunteer, namun tidak semua tim menggunakan bantuan volunteer. Hasil kegiatan dari setiap tim dapat diwujudkan ke dalam sebuah pengakuan hak cipta atau publikasi karya ilmiah atau publikasi berita di media massa.

## Ketentuan
1. Pengerjaan secara individu alias setiap mahasiswa!
2. Terdapat data dengan nilai #N/A, pertimbangkan cara terbaik untuk mengatasi nilai tersebut.
3. Tidak boleh ada duplikasi pekerjaan antar mahasiswa
4. Berikan penjelasan untuk setiap tahapan. Jangan hanya kode!

## Soal
1. Lakukan pemilahan data training dan testing yang sesuai dan proporsional dari data tersebut! (10 poin)
2. Tentukan data validasi! (10 poin)
3. Tentukan secara tepat kolom yang menjadi "label" (20 poin)
4. Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi  dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan! (20 poin)
5. Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya. (40 poin)

In [2]:
import pandas as pd

df = pd.read_excel('dataset_quiz.xlsx')

df.head(100)

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,id_anggota5,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
1,7214.0,7109.0,8402.0,7903.0,9202.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
2,5911.0,8201.0,8701.0,9101.0,9003.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
3,8402.0,7702.0,8602.0,8903.0,8903.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
4,8201.0,8305.0,5911.0,5903.0,8402.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,8803.0,8804.0,9102.0,8005.0,9303.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
81,6211.0,8901.0,9003.0,9303.0,9007.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
82,8601.0,8903.0,8703.0,NaN,NaN,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
83,8703.0,8601.0,9202.0,9102.0,6204.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
84,8102.0,7109.0,5903.0,7206.0,8903.0,NaN,TIDAK,0,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA

1. Lakukan pemilahan data training dan testing yang sesuai dan proporsional dari data tersebut! (10 poin)

In [5]:
df.isna().sum()

id_ketua               3
id_anggota1            5
id_anggota2            4
id_anggota3            3
id_anggota4           13
id_anggota5           84
keterlibatan_vltr      0
jml_vltr_terlibat      0
tahun                  0
skema                  0
luaran_hki             0
jenis_luaran_hki       0
potensi_hki            0
luaran_lain            0
jenis_luaran_lain      0
status_luaran_lain     0
dtype: int64

In [6]:
# Menghilangkan data null
df.drop('id_anggota5', axis=1, inplace=True)

modus_ketua = df['id_ketua'].mode()[0]
df['id_ketua'] = df['id_ketua'].fillna(modus_ketua)

modus_anggota1 = df['id_anggota1'].mode()[0]
df['id_anggota1'] = df['id_anggota1'].fillna(modus_anggota1)

modus_anggota2 = df['id_anggota2'].mode()[0]
df['id_anggota2'] = df['id_anggota2'].fillna(modus_anggota2)

modus_anggota3 = df['id_anggota3'].mode()[0]
df['id_anggota3'] = df['id_anggota3'].fillna(modus_anggota3)

modus_anggota4 = df['id_anggota4'].mode()[0]
df['id_anggota4'] = df['id_anggota4'].fillna(modus_anggota4)
# Cek Data
df.head()

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,0,0,2019,1,1,1,2,0,3,1
1,7214.0,7109.0,8402.0,7903.0,9202.0,0,0,2019,1,1,1,2,0,3,1
2,5911.0,8201.0,8701.0,9101.0,9003.0,0,0,2019,1,1,1,2,0,3,1
3,8402.0,7702.0,8602.0,8903.0,8903.0,0,0,2019,1,1,1,2,0,3,1
4,8201.0,8305.0,5911.0,5903.0,8402.0,0,0,2019,1,1,1,2,0,3,1

In [7]:
df.isna().sum()

id_ketua              0
id_anggota1           0
id_anggota2           0
id_anggota3           0
id_anggota4           0
keterlibatan_vltr     0
jml_vltr_terlibat     0
tahun                 0
skema                 0
luaran_hki            0
jenis_luaran_hki      0
potensi_hki           0
luaran_lain           0
jenis_luaran_lain     0
status_luaran_lain    0
dtype: int64

In [13]:
# Melakukan Pemilahan data Training dan Testing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['skema']=encoder.fit_transform(df['skema'])
df['luaran_hki']=encoder.fit_transform(df['luaran_hki'])
df['jenis_luaran_hki']=encoder.fit_transform(df['jenis_luaran_hki'])
df['potensi_hki']=encoder.fit_transform(df['potensi_hki'])
df['luaran_lain']=encoder.fit_transform(df['luaran_lain'])
df['jenis_luaran_lain']=encoder.fit_transform(df['jenis_luaran_lain'])
df['status_luaran_lain']=encoder.fit_transform(df['status_luaran_lain'])
df['keterlibatan_vltr']=encoder.fit_transform(df['keterlibatan_vltr'])

X = df.drop(['keterlibatan_vltr'], axis=1)
y = df['keterlibatan_vltr']

X = pd.get_dummies(X)

2.Tentukan data validasi! (10 poin)

In [9]:
# Implementasi k-fold cross validation stratified dengan data training, validation, dan testing
from sklearn.model_selection import train_test_split, StratifiedKFold
# Melakukan Normalisasi Data
from sklearn.preprocessing import MinMaxScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Split train test
# Rasio 8:2
df_train2, df_test2 = train_test_split(df, test_size=0.2, random_state=0)

# inisiasi obyek StratifiedKFold
# dengan data df_train2
skf2 = StratifiedKFold(n_splits=4)
print(f'Jumlah fold: {skf2.get_n_splits()}')
print(f'Obyek SKFold: {skf2}')

# Lakukan splitting dengan SKFold
# parameter kedua dari split adalah labelnya
# Split train menjadi train dan validasi
skf2_split = skf2.split(df_train2, df_train2['keterlibatan_vltr'])
print(f'Jumlah data df: {len(df_train2)}')

# cek index data tiap fold
for train_index, test_index in skf2_split:
    print(f'Index train: {train_index} | Index test:{test_index}')

Jumlah fold: 4
Obyek SKFold: StratifiedKFold(n_splits=4, random_state=None, shuffle=False)
Jumlah data df: 68
Index train: [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 31 32 33 35 36 37 39
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[17 18 19 20 21 22 23 24 25 26 27 28 29 30 34 38 40]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 34 38 40 50 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[31 32 33 35 36 37 39 41 42 43 44 45 46 47 48 49 51]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 51] | Index test:[50 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67]

4.Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan! (20 poin)

In [14]:
# Meneraplkan Dua Jenis Algoritma Klasifikasi
# 1. KNN
# 2. Random Forest

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# KNN
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
print('KKN')
print('Akurasi Score : ',accuracy_score(y_test, pred))

# Random Forest
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

print('Random Forest')
print('Akurasi Score : ',accuracy_score(y_test, rfc_pred))

# Melakukan Perbandingan antara KNN dan Random Forest
print('Perbandingan antara KNN dan Random Forest : ',(accuracy_score(y_test, pred)-accuracy_score(y_test, rfc_pred)))

KKN
Akurasi Score :  0.8823529411764706
Random Forest
Akurasi Score :  1.0
Perbandingan antara KNN dan Random Forest :  -0.11764705882352944

5.Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya.

In [21]:
# lakukan hyperparameter tuning Menggunakan Metode Grid Search dan Randomized Search
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

parameter = {    
    'criterion': ['gini', 'entropy'],
    'max_depth': list(range(5,11))
    
    }

grid = GridSearchCV(RandomForestClassifier(),param_grid=parameter,cv=skf2)
grid.fit(X_train, y_train)

%timeit grid.fit(X, y)

score = grid.score(X,y)

print('Random Forest')
print('GridSearchCV')
print(f'Hasil evaluasi: {score}')
print(f'Konfigurasi hyperparameter: {grid.best_params_}')

7.22 s Â± 33.9 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)
Random Forest
GridSearchCV
Hasil evaluasi: 1.0
Konfigurasi hyperparameter: {'criterion': 'gini', 'max_depth': 6}

In [22]:
# RandomizedSearch
# Mencari parameter terbaik untuk Random Forest
param_grid = {
    'bootstrap': [True, False],
    'random_state': [42, 43, 44, 45, 46, 47, 48, 49, 50],
    'max_depth': [60,70,80, 90],
}

random = RandomizedSearchCV(RandomForestClassifier(),param_grid,refit=True,cv=skf2,scoring='accuracy')
random.fit(X_train, y_train)

%timeit random.fit(X, y)

# Evaluasi dengan score
score = random.score(X,y)

print('Random Forest')
print('RandomizedSearch')
print(f'Hasil evaluasi: {score}')
print(f'Konfigurasi hyperparameter: {random.best_params_}')

5.21 s Â± 113 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)
Random Forest
RandomizedSearch
Hasil evaluasi: 1.0
Konfigurasi hyperparameter: {'random_state': 46, 'max_depth': 80, 'bootstrap': False}

kesimpulan kedua method menghasilkan hasil evaluasi yang sama akan tetapi saya mencurigai antara algoritma terlalu bagus / mesin menghafal data training