## **Kuis**
*Nama  :* Reynaldi Fakrhi Pratama<br>
*Kelas :* TI-3A/27<br>
*NIM   :* 2041720209<br>

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [21]:
# read data bahan kuis
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Mapping data

In [22]:
new_labels_sex = {
    'male': 1,
    'female': 0
}

new_labels_smoker ={
    'yes' : 1,
    'no' : 0
}

new_labels_region ={
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
}

# Encode label
df['sex'] = df['sex'].map(new_labels_sex)
df['smoker'] = df['smoker'].map(new_labels_smoker)
df['region'] = df['region'].map(new_labels_region)


# Cek data
df.head()
databaru2 = df

fungsi ini digunakan untuk menjawab soal 2,3 dan 4

In [23]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
  
# the independent variables set
X = df[['age', 'bmi', 'region','sex', 'smoker', 'children']]
  
# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
  
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(vif_data)

    feature       VIF
0       age  7.588734
1       bmi  9.938670
2    region  2.789478
3       sex  2.002652
4    smoker  1.261195
5  children  1.799980

In [24]:
df = df.drop(df.columns[0], axis=1)
df = df.drop(df.columns[1], axis=1)
df.head()

   sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

In [25]:
databaru = df
databaru.head()

   sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

In [26]:
X = databaru.iloc[:, :-1].values
y = databaru.iloc[:, 4].values

kode dibawah ini merupakan jawaban dari langkah2 R2 soal no 5

In [27]:
Xm_train, Xm_test, ym_train, ym_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [28]:
y = y.reshape(len(y), 1)
y.shape

(1338, 1)

In [29]:
mlr = LinearRegression()
mlr.fit(Xm_train, ym_train)

ym_pred = mlr.predict(Xm_test)

In [30]:
combine = np.concatenate((ym_test, ym_pred))
combine

array([ 1826.843     , 20177.67113   ,  7421.19455   ,  1877.9294    ,
       15518.18025   , 29523.1656    , 13143.86485   ,  3279.86855   ,
       18972.495     , 12950.0712    ,  8083.9198    , 18218.16139   ,
        8334.45755   ,  2727.3951    ,  7441.053     , 38711.        ,
       10338.9316    , 11552.904     ,  4751.07      , 11381.3254    ,
       10226.2842    ,  1526.312     ,  7222.78625   , 21259.37795   ,
       10848.1343    , 58571.07448   ,  3268.84665   , 48517.56315   ,
       21880.82      , 13457.9608    , 12592.5345    ,  2457.21115   ,
       47896.79135   , 33732.6867    ,  6600.361     , 14349.8544    ,
       18963.17192   , 39047.285     ,  3645.0894    , 30942.1918    ,
        7624.63      ,  7650.77375   ,  2498.4144    ,  4949.7587    ,
        2196.4732    ,  3972.9247    ,  4415.1588    ,  2362.22905   ,
       11272.33139   ,  5662.225     , 13405.3903    ,  8269.044     ,
        4915.05985   ,  7729.64575   ,  7045.499     , 11674.13      ,
       10085.846     , 37607.5277    ,  6313.759     , 20781.48892   ,
       24059.68019   ,  2741.948     , 18157.876     ,  8280.6227    ,
       11987.1682    ,  2690.1138    ,  2198.18985   ,  5246.047     ,
        4686.3887    , 45863.205     ,  9861.025     ,  5354.07465   ,
       12957.118     , 17361.7661    ,  8823.98575   ,  1708.0014    ,
       25992.82104   , 24180.9335    , 13352.0998    ,  9101.798     ,
        2639.0429    , 19214.70553   ,  7201.70085   ,  3392.3652    ,
       35069.37452   , 45008.9555    , 12146.971     , 40003.33225   ,
       17904.52705   ,  6334.34355   , 17043.3414    ,  8233.0975    ,
        9644.2525    ,  1252.407     , 37270.1512    ,  6282.235     ,
        8347.1643    ,  6196.448     , 19023.26      ,  4827.90495   ,
        5615.369     ,  2166.732     , 10141.1362    ,  8605.3615    ,
       39722.7462    , 12643.3778    , 35585.576     , 19798.05455   ,
       12574.049     ,  1981.5819    , 11187.6567    ,  5257.50795   ,
       11455.28      , 10965.446     , 22144.032     , 13974.45555   ,
        1909.52745   , 13831.1152    ,  8596.8278    ,  7623.518     ,
       20984.0936    , 12404.8791    , 14007.222     , 13112.6048    ,
        9722.7695    , 24915.22085   , 11353.2276    , 24671.66334   ,
        6640.54485   , 10355.641     ,  4189.1131    ,  6775.961     ,
        5031.26955   , 10713.644     ,  1391.5287    , 34806.4677    ,
       12094.478     , 36837.467     ,  6652.5288    ,  7742.1098    ,
       38344.566     ,  2494.022     , 34779.615     ,  7639.41745   ,
        6123.5688    ,  9140.951     , 12142.5786    ,  4040.55825   ,
        9964.06      ,  7682.67      , 12479.70895   ,  3558.62025   ,
        4883.866     , 10065.413     , 11454.0215    ,  9715.841     ,
       38746.3551    ,  9249.4952    , 11085.5868    , 18310.742     ,
        8944.1151    , 33750.2918    , 39241.442     , 10736.87075   ,
        3956.07145   , 11362.755     ,  1131.5066    ,  8116.26885   ,
       16069.08475   , 12644.589     , 47403.88      , 33907.548     ,
        4350.5144    , 32548.3405    ,  7512.267     , 13725.47184   ,
        2055.3249    , 32787.45859   , 14590.63205   ,  7323.734819  ,
       39725.51805   , 17085.2676    , 20149.3229    , 12949.1554    ,
        2902.9065    , 17352.6803    , 34672.1472    , 10825.2537    ,
        6389.37785   , 14692.66935   ,  1242.816     ,  9447.25035   ,
        2130.6759    ,  9500.57305   ,  4846.92015   ,  6414.178     ,
       46113.511     , 12829.4551    ,  9282.4806    , 12323.936     ,
        2867.1196    ,  5253.524     ,  1977.815     ,  7358.17565   ,
       48970.2476    , 60021.39897   , 10197.7722    , 26926.5144    ,
        2457.502     , 37701.8768    ,  9778.3472    ,  1986.9334    ,
       15817.9857    , 29141.3603    ,  7162.0122    ,  6113.23105   ,
       18806.14547   ,  5377.4578    ,  1824.2854    ,  2709.24395   ,
       12629.8967    , 14313.8463    ,  5584.3057    ,  7626.993     ,
        8601.3293    , 47462.894     ,  3989.841     ,  2045.68525   ,
       13607.36875   ,  5757.41345   , 10942.13205   , 40103.89      ,
       43921.1837    ,  8059.6791    ,  4500.33925   , 40974.1649    ,
        3171.6149    ,  6748.5912    , 13019.16105   ,  7147.105     ,
       14358.36437   ,  2150.469     ,  4906.40965   , 42211.1382    ,
        5002.7827    ,  7046.7222    ,  1639.5631    , 31620.00106   ,
        9788.8659    ,  3443.064     , 16796.41194   ,  5003.853     ,
        2855.43755   , 11244.3769    , 11396.9002    , 26125.67477   ,
        3866.8552    , 11070.535     , 36197.699     ,  6455.86265   ,
        2709.1119    , 38998.546     ,  7151.092     ,  1984.4533    ,
       14283.4594    , 14043.4767    ,  8825.086     , 12124.9924    ,
        7757.70618263,  8849.60100365,  7379.7890171 ,  7823.25191958,
       31512.69007566, 31356.50436137,  8201.16908511,  9449.24962043,
       32539.03915974,  7535.97473139,  8603.47790153,  8447.29218724,
        8825.20935277,  8201.16908511,  8381.74645029, 32317.3077085 ,
        7823.25191958, 10721.72180662,  8381.74645029,  7979.43763387,
        7979.43763387,  7757.70618263,  7535.97473139, 32760.77061098,
        8627.86955241, 31980.54462903,  8201.16908511, 31980.54462903,
       31939.39054296,  7823.25191958, 10943.45325787,  8044.98337082,
       31980.54462903, 31512.69007566,  9005.78671795,  8160.01499905,
        8603.47790153, 32136.73034332,  8201.16908511, 33006.8937131 ,
        8225.56073599,  8669.02363848,  7979.43763387,  9071.33245489,
        8044.98337082,  7823.25191958,  7823.25191958,  8160.01499905,
        8825.20935277,  7823.25191958,  7979.43763387,  7601.52046834,
       11321.3704234 ,  9449.24962043,  8225.56073599,  8225.56073599,
        8381.74645029, 32136.73034332,  9071.33245489,  7979.43763387,
        8627.86955241,  8044.98337082,  8784.0552667 ,  7823.25191958,
        9851.55843684,  7379.7890171 ,  8044.98337082,  8225.56073599,
        9227.51816919, 31134.77291013,  8225.56073599,  8669.02363848,
        7757.70618263, 32095.57625726,  8669.02363848,  8201.16908511,
        9851.55843684, 33006.8937131 ,  7535.97473139,  9473.64127131,
        8160.01499905,  7979.43763387,  8627.86955241,  8447.29218724,
       31512.69007566, 31134.77291013,  7757.70618263, 31939.39054296,
       31512.69007566,  9917.10417379, 31290.95862442,  8447.29218724,
        7379.7890171 ,  7757.70618263, 31356.50436137,  8381.74645029,
        9227.51816919,  9473.64127131, 34033.24279718, 10073.28988809,
       10877.90752092,  7601.52046834, 10073.28988809,  9851.55843684,
       31290.95862442,  8627.86955241, 31069.22717318, 32604.58489669,
        7757.70618263,  7979.43763387,  8627.86955241,  8784.0552667 ,
        7601.52046834,  7757.70618263, 31069.22717318,  8201.16908511,
        7535.97473139,  7979.43763387, 10943.45325787,  8225.56073599,
       32760.77061098,  8201.16908511,  9473.64127131,  8160.01499905,
        8201.16908511, 32719.61652491,  7535.97473139, 10541.14444145,
        9449.24962043,  7379.7890171 ,  8627.86955241,  8225.56073599,
        9449.24962043,  7601.52046834,  7979.43763387, 31914.99889208,
        9473.64127131, 31069.22717318,  9851.55843684,  8603.47790153,
       32317.3077085 ,  7757.70618263, 31069.22717318,  8669.02363848,
        8160.01499905,  7979.43763387,  7979.43763387,  8825.20935277,
        8825.20935277,  9695.37272255,  9251.90982007,  8044.98337082,
        7601.52046834,  8381.74645029,  7379.7890171 ,  9293.06390613,
       32719.61652491,  8003.82928475,  9251.90982007, 30847.49572194,
        9851.55843684, 30847.49572194, 32317.3077085 , 10697.33015574,
        8003.82928475,  7757.70618263,  7979.43763387,  8784.0552667 ,
        9293.06390613,  7601.52046834, 31693.26744084, 30691.31000765,
        8447.29218724, 31290.95862442, 10253.86725326,  8669.02363848,
        7535.97473139, 32719.61652491,  9917.10417379,  8044.98337082,
       31315.3502753 , 31758.81317779, 31512.69007566, 10475.5987045 ,
        8603.47790153, 30847.49572194, 31290.95862442,  8160.01499905,
        8160.01499905,  7379.7890171 ,  7757.70618263,  8669.02363848,
        7379.7890171 , 10073.28988809, 10073.28988809,  9473.64127131,
       32161.1219942 , 32760.77061098,  8825.20935277,  8201.16908511,
        7979.43763387,  9629.8269856 ,  7757.70618263,  8669.02363848,
       31914.99889208, 32719.61652491,  8044.98337082, 31290.95862442,
        7601.52046834, 31980.54462903,  8669.02363848,  7979.43763387,
       30847.49572194, 30691.31000765,  9227.51816919,  9917.10417379,
        9227.51816919,  8160.01499905,  7979.43763387,  8003.82928475,
        7823.25191958,  7823.25191958,  9227.51816919,  8225.56073599,
        7823.25191958, 32539.03915974,  7601.52046834,  7535.97473139,
        9293.06390613,  8201.16908511,  8003.82928475, 32317.3077085 ,
       30847.49572194,  9251.90982007,  8201.16908511, 31134.77291013,
        7823.25191958, 10073.28988809,  8669.02363848,  7757.70618263,
        8381.74645029,  7601.52046834,  8627.86955241, 31914.99889208,
        8447.29218724,  8447.29218724,  7535.97473139,  8669.02363848,
       11099.63897216,  9629.8269856 ,  8669.02363848,  8225.56073599,
        7379.7890171 ,  9449.24962043,  9293.06390613, 31134.77291013,
        7535.97473139,  7601.52046834, 31069.22717318,  8784.0552667 ,
        8003.82928475, 32317.3077085 ,  9473.64127131,  8201.16908511,
       31356.50436137,  8044.98337082,  8849.60100365,  7535.97473139])

In [31]:
r2_mlr = r2_score(ym_test, ym_pred)
print(r2_mlr)

0.6835825358097569

Soal 6 simpulan hasil regresi terbaik

In [32]:

databaru2.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [33]:
X2 = databaru2.iloc[:, :-1].values
y2 = databaru2.iloc[:, 6].values

In [36]:
Xm_train2, Xm_test2, ym_train2, ym_test2 = train_test_split(X2, y2, test_size=0.2, random_state=50)

In [37]:
y2 = y2.reshape(len(y2), 1)
y2.shape

(1338, 1)

In [39]:
mlr2 = LinearRegression()
mlr2.fit(Xm_train2, ym_train2)

ym_pred2 = mlr2.predict(Xm_test2)

In [40]:
combine2 = np.concatenate((ym_test2, ym_pred2))
combine2

array([ 5.97683110e+03,  5.84691760e+03,  1.38311152e+04,  9.62592000e+03,
        2.68094930e+03,  4.78967913e+04,  1.82234512e+04,  7.41947790e+03,
        3.73262510e+03,  1.22228983e+04,  7.05002130e+03,  2.19786769e+04,
        6.28223500e+03,  3.77018768e+04,  7.04672220e+03,  1.20323260e+04,
        1.31126048e+04,  4.23989265e+03,  1.23338280e+04,  3.41032400e+03,
        1.72778500e+03,  4.46411974e+04,  1.71284261e+04,  6.11235295e+03,
        4.52947700e+03,  1.05945016e+04,  6.40229135e+03,  4.61511245e+04,
        1.71102680e+03,  1.70470015e+03,  4.58632050e+04,  4.68779700e+03,
        1.50197601e+04,  3.18051010e+03,  3.86120965e+03,  3.44306400e+03,
        2.71179938e+04,  2.70924395e+03,  1.34511220e+04,  4.79280300e+04,
        2.35630162e+04,  6.71019190e+03,  1.42350720e+04,  1.40011338e+04,
        2.72184372e+04,  1.33905590e+04,  4.10342214e+04,  2.02017700e+03,
        1.42561928e+04,  2.12321823e+04,  4.86755177e+04,  6.98669700e+03,
        4.14973600e+03,  3.09421918e+04,  8.02313545e+03,  4.21245153e+04,
        1.18371600e+04,  6.64054485e+03,  6.66624300e+03,  1.08481343e+04,
        1.43943982e+04,  7.20170085e+03,  1.97781500e+03,  1.63573365e+03,
        7.25672310e+03,  8.53828845e+03,  3.85775925e+03,  9.88006800e+03,
        4.88386600e+03,  2.17970004e+04,  1.38809490e+04,  4.77960230e+03,
        3.48186800e+03,  5.39761670e+03,  9.58389330e+03,  1.70810800e+04,
        6.60036100e+03,  9.71584100e+03,  2.43936224e+04,  1.63182120e+03,
        2.85068375e+03,  1.82464955e+04,  2.45750200e+03,  1.29287911e+04,
        1.96702270e+03,  2.64326850e+03,  1.19871682e+04,  4.87798105e+03,
        3.04606200e+03,  4.54423480e+03,  3.73646470e+03,  8.59682780e+03,
        3.75662160e+03,  3.60210112e+04,  2.45202640e+04,  1.13059345e+04,
        7.51226700e+03,  1.20944780e+04,  1.62978460e+04,  2.32889284e+04,
        2.46716633e+04,  2.20109710e+03,  4.39211837e+04,  1.43827090e+04,
        1.71795220e+04,  8.54769130e+03,  3.87091760e+04,  9.95772160e+03,
        9.91035985e+03,  5.64971500e+03,  5.48826200e+03,  8.98815875e+03,
        1.82684300e+03,  1.83728190e+03,  1.63956310e+03,  4.93470500e+03,
        5.42502335e+03,  2.89231369e+04,  1.42105359e+04,  2.41069126e+04,
        1.52631200e+03,  5.32740025e+03,  1.13639940e+03,  1.62543375e+03,
        1.18819696e+04,  4.53625900e+03,  7.28150560e+03,  8.83526495e+03,
        8.06276400e+03,  3.59148000e+03,  4.86735588e+04,  1.12891092e+04,
        4.62009851e+04,  2.42273372e+04,  2.02348547e+04,  2.48698368e+04,
        2.00096336e+04,  6.55507035e+03,  8.27752300e+03,  4.57141305e+03,
        1.26221795e+04,  4.18509790e+03,  5.31216985e+03,  1.88047524e+04,
        6.74859120e+03,  7.16201220e+03,  5.24522690e+03,  8.51575870e+03,
        6.85847960e+03,  4.34946200e+03,  4.09741649e+04,  4.43391590e+03,
        1.98007000e+03,  5.11945591e+04,  2.02697410e+03,  2.73460421e+04,
        1.31266774e+04,  2.04629977e+04,  2.02968635e+04,  1.22445310e+04,
        7.74033700e+03,  9.77834720e+03,  5.58430570e+03,  1.09593300e+04,
        2.72132080e+03,  5.00385300e+03,  6.79686325e+03,  1.76953165e+03,
        2.13487060e+04,  1.62218850e+03,  4.88851356e+04,  2.24936596e+04,
        1.26298967e+04,  7.33774800e+03,  3.99834259e+04,  1.39152870e+03,
        4.10971617e+04,  7.68267000e+03,  3.71651638e+04,  9.56302900e+03,
        1.02146360e+04,  1.26462070e+04,  5.69983750e+03,  1.10137119e+04,
        1.94423535e+04,  4.44238030e+04,  4.27605022e+04,  9.30189355e+03,
        3.98365190e+04,  1.01567832e+04,  4.43338770e+03,  3.77425757e+04,
        8.78246900e+03,  1.15124050e+04,  2.55171136e+04,  1.08068390e+04,
        3.97742763e+04,  5.38533790e+03,  2.12843105e+03,  3.72701512e+04,
        3.33075508e+04,  1.29571180e+04,  7.72725320e+03,  1.18564115e+04,
        5.72900530e+03,  1.58206990e+04,  9.44738240e+03,  1.26381950e+04,
        4.42607499e+04,  1.09772063e+04,  1.91077796e+04,  1.49884320e+04,
        9.63039700e+03,  4.72698540e+04,  1.30638830e+04,  1.82428540e+03,
        1.17630009e+04,  9.86102500e+03,  3.69502567e+04,  2.10308000e+03,
        2.19818985e+03,  3.84154740e+04,  8.62754110e+03,  4.23712655e+03,
        4.44121315e+03,  9.87270100e+03,  3.21086628e+04,  2.08787844e+04,
        2.69956835e+03,  7.73185785e+03,  2.10821600e+04,  2.73010785e+03,
        1.13267149e+04,  3.92575820e+03,  3.82827495e+04,  1.22358392e+04,
        1.01150089e+04,  8.93208400e+03,  1.40012867e+04,  3.55955898e+04,
        1.52303240e+04,  6.05917300e+03,  2.16673200e+03,  8.94411510e+03,
        4.05811610e+03,  1.23239360e+04,  3.37326867e+04,  5.37503800e+03,
        1.97295000e+03,  1.07044700e+04,  1.18426238e+04,  3.86685520e+03,
        6.12879745e+03,  1.10705350e+04,  1.05604917e+04,  1.19382560e+04,
        1.27411675e+04,  1.17296795e+04,  2.36222905e+03,  9.50057305e+03,
        6.18429940e+03,  1.38879685e+04,  1.32246930e+04,  3.39236520e+03,
        4.93164700e+03,  9.72453000e+03,  3.65802822e+04,  3.71338982e+04,
        8.02669491e+03,  1.16938407e+04,  1.71786170e+04,  1.13687219e+04,
        4.67609884e+02,  3.87045302e+04,  2.62413412e+04,  7.89114229e+03,
        7.64340489e+02,  1.16795655e+04,  9.23505349e+03,  3.20389021e+04,
        8.15323277e+03,  3.08375213e+04,  7.61558919e+03,  9.55980129e+03,
        1.16167569e+04,  4.77694453e+03,  1.23046130e+04,  8.74838942e+03,
       -1.22879102e+03,  3.65374536e+04,  6.53621123e+03,  8.97898395e+03,
        4.31574332e+03,  1.09692130e+04,  5.35105861e+03,  3.79991539e+04,
        5.29104947e+02, -3.93428374e+01,  3.72628449e+04,  4.33743188e+03,
        1.46054920e+04,  1.36853647e+03,  1.11298477e+03,  6.09495004e+03,
        9.30224165e+03,  1.41540873e+03,  1.19443733e+04,  3.91617990e+04,
        9.68824527e+03,  6.78513321e+03,  1.70073442e+04,  1.32724110e+04,
        3.52055455e+04,  1.39302242e+04,  3.39789701e+04,  4.58596872e+03,
        1.26466707e+04,  9.74933525e+03,  3.98559896e+04,  9.49978725e+03,
        6.60275122e+03,  3.79738009e+04,  1.16535772e+04,  3.52230801e+04,
        1.09937604e+04,  3.91030773e+03,  1.21456900e+04,  1.37684916e+04,
        1.34694008e+04,  7.45548672e+03,  3.57174222e+03,  1.90502761e+03,
        9.21297345e+03,  1.03640638e+04,  5.71671612e+03,  1.41684121e+04,
        5.73379540e+03,  1.50016528e+04,  1.43462428e+04,  5.99485843e+03,
        3.56420413e+03,  9.82013498e+03,  1.22304916e+04,  2.55880331e+04,
        8.67812632e+03,  9.38294791e+03,  3.36182301e+04,  4.92489598e+03,
        3.93267720e+03,  2.77207188e+04,  1.55499215e+03,  1.40274229e+04,
        1.99830658e+03,  4.20672752e+03,  1.41047497e+04,  4.78877623e+03,
        2.69197734e+03,  2.79864120e+03,  3.96932743e+03,  1.11502443e+04,
        4.25781375e+03,  2.88154796e+04,  3.36546406e+04,  1.12466428e+04,
        9.19150387e+03,  1.05772988e+04,  2.52983921e+04,  3.41623227e+03,
        5.88257017e+03,  8.72456429e+02,  3.66130005e+04,  1.30753592e+04,
        2.84923035e+04,  9.89070254e+03,  3.23440392e+04,  1.02260455e+04,
        1.10132228e+04,  8.57937692e+03,  8.08795831e+03,  1.02689374e+04,
        4.92960613e+03,  7.23895007e+03,  2.77545328e+03,  5.20177692e+03,
        7.25934832e+03,  1.17662608e+04,  1.64918520e+04,  3.29496410e+04,
        3.38009016e+03,  7.46888157e+03,  3.36516016e+03, -4.36117309e+02,
        1.25923883e+04,  1.08338901e+04,  7.82961165e+03,  1.11426655e+04,
        1.07797392e+04,  5.68491809e+03,  3.98032430e+04,  1.31220711e+04,
        3.76480758e+04,  1.62097890e+04,  2.96197505e+04,  3.37599910e+04,
        2.96370016e+04,  6.88119140e+03,  9.62824908e+03,  5.19323182e+03,
        1.32536617e+04,  4.31291467e+03,  5.09833779e+03,  6.13551855e+03,
        7.64607665e+03,  1.14217040e+04,  8.37846651e+03,  9.32805357e+03,
        6.49095427e+03,  6.65282700e+03,  3.43943902e+04,  6.65180339e+03,
        4.15773890e+03,  3.07589640e+04,  6.06753943e+03,  1.15060939e+04,
        3.00763925e+03,  1.50185694e+04,  2.95868891e+04,  1.43432553e+04,
        1.19667246e+04,  1.07796890e+04,  9.03215556e+03,  1.01663194e+04,
        2.72529442e+03,  6.06842734e+03,  8.72002142e+03,  2.75877159e+03,
        3.09436831e+04,  2.73540417e+03,  3.49445113e+04,  2.58655069e+03,
        1.12255834e+04,  9.10774659e+03,  3.28331066e+04,  3.76779947e+03,
        3.43318330e+04,  1.01250375e+04,  2.95603179e+04,  1.25266887e+04,
        1.16182713e+04,  1.56460042e+04,  9.15976575e+03,  9.35429467e+03,
        7.04199421e+03,  3.68288660e+04,  3.55870975e+04,  9.38028248e+03,
        3.30653875e+04,  8.99950643e+03,  6.53174468e+03,  3.16699567e+04,
        9.18272175e+03,  1.25271759e+04,  1.02660445e+04,  1.28938154e+04,
        3.24916310e+04,  5.78744377e+03,  2.84551322e+03,  3.08068908e+04,
        2.61948521e+04,  1.07069003e+04,  1.06497598e+04,  1.53061892e+04,
        9.01291684e+03,  2.74600204e+04,  9.44571018e+03,  1.31751644e+04,
        3.70241676e+04,  1.55129423e+04,  2.83762076e+04,  1.34023770e+04,
        1.19708960e+04,  3.89152816e+04,  1.76938586e+04,  4.28487383e+03,
        1.28739728e+04,  9.83997953e+03,  3.04967926e+04,  1.03058868e+03,
        1.08123084e+03,  3.22695409e+04,  6.51092281e+03,  4.87357222e+03,
        4.88690520e+03,  1.24939090e+04,  9.51300646e+03,  1.06523789e+04,
        4.69967954e+03,  1.11160459e+04,  3.09877723e+04,  6.15772793e+03,
        1.03780289e+04,  5.56792066e+03,  3.17574571e+04,  1.46210039e+04,
        1.23150698e+04,  9.09253475e+03,  1.33071649e+04,  2.84367733e+04,
        1.68164802e+04,  7.60761261e+03,  5.28174071e+03,  1.49862953e+04,
        8.16160248e+03,  1.08623735e+04,  2.61914052e+04,  7.95188002e+03,
        2.46593828e+03,  1.19079123e+04,  1.28968343e+04,  5.53004440e+03,
        8.27319627e+03,  1.05184540e+04,  1.29171789e+04,  1.23797891e+04,
        1.49877174e+04,  1.00032100e+04,  4.02998816e+03,  8.88994958e+03,
        7.42270453e+03,  1.58783645e+04,  1.30372708e+04,  4.60299778e+03,
        4.50670015e+03,  1.13835089e+04,  1.59825632e+04,  3.00102852e+04])

In [41]:
r2_mlr2 = r2_score(ym_test2, ym_pred2)
print(r2_mlr2)

0.7835627749480736

nilai VIF yang kurang dari 5 tidak lebih baik daripada nilai yang mengunakan semua kolom